### ISSUE TITLE
error 1022 Please provide 'code' on proxmox 8 (duplicate #27)

### ISSUE THREAD

**Issue by stef-pellegrino** [lneely/pcloudcc-lneely#72] opened 2024-11-25 14:54 UTC
Hi,

I'm under promox 8.3, and each time I try to connect to pcloud, I hang on "CONNECTING":

```
$ pcloudcc -u <login> -s -p
pCloud console client (git-lneely)
Please, enter password
Down: Everything Downloaded| Up: Everything Uploaded, status is LOGIN_REQUIRED
logging in
Down: Everything Downloaded| Up: Everything Uploaded, status is CONNECTING

```
The log gives me :

```
NOTICE: pclsync/pdiff.c:424 (function get_connected_socket): userinfo returned error 1022 Please provide 'code'.
s change NOTICE: pclsync/pcallbacks.c:294 (function status_change_thread): sending status update, dwlstr: Everything Downloaded, uplstr: Everything Uploaded
scan NOTICE: pclsync/plocalscan.c:1058 (function scanner_scan): run checks
NOTICE: pclsync/pcompat.c:866 (function connect_socket_direct): connecting to bineapi.pcloud.com:443
NOTICE: pclsync/pcompat.c:889 (function connect_socket_direct): successfully reused cached IP for bineapi.pcloud.com:443
NOTICE: pclsync/pssl.c:438 (function psync_ssl_connect): reusing cached session for bineapi.pcloud.com
NOTICE: pclsync/pcompat.c:2382 (function psync_deviceid): detected device: Desktop, Linux
NOTICE: pclsync/pdiff.c:183 (function get_userinfo_user_pass): got digest pCloudpCloudpCloudZQuLykFhWtVhZUioJXkZGTiOda4Rv2RgohKOjQeIaz
NOTICE: pclsync/pdiff.c:424 (function get_connected_socket): userinfo returned error 1022 Please provide 'code'.
NOTICE: pclsync/pcompat.c:866 (function connect_socket_direct): connecting to bineapi.pcloud.com:443
...
NOTICE: pclsync/pdiff.c:424 (function get_connected_socket): userinfo returned error 1022 Please provide 'code'.
NOTICE: pclsync/pcompat.c:866 (function connect_socket_direct): connecting to bineapi.pcloud.com:443
NOTICE: pclsync/pcompat.c:889 (function connect_socket_direct): successfully reused cached IP for bineapi.pcloud.com:443
NOTICE: pclsync/pssl.c:438 (function psync_ssl_connect): reusing cached session for bineapi.pcloud.com
NOTICE: pclsync/pcompat.c:2382 (function psync_deviceid): detected device: Desktop, Linux
NOTICE: pclsync/pdiff.c:183 (function get_userinfo_user_pass): got digest pCloudpCloudpCloudZ5agyWvFVBpjZcioJXkZEN2FeattzC5oVwVWu2PFxf
NOTICE: pclsync/pdiff.c:424 (function get_connected_socket): userinfo returned error 1022 Please provide 'code'.
NOTICE: pclsync/pcompat.c:866 (function connect_socket_direct): connecting to bineapi.pcloud.com:443
NOTICE: pclsync/pcompat.c:889 (function connect_socket_direct): successfully reused cached IP for bineapi.pcloud.com:443
NOTICE: pclsync/pssl.c:438 (function psync_ssl_connect): reusing cached session for bineapi.pcloud.com
NOTICE: pclsync/pcompat.c:2382 (function psync_deviceid): detected device: Desktop, Linux
NOTICE: pclsync/pdiff.c:183 (function get_userinfo_user_pass): got digest pCloudpCloudpCloudZK7add0w2U4pZXroJXkZYb56d0r3XRHHP4xmRPBLaY
NOTICE: pclsync/pdiff.c:424 (function get_connected_socket): userinfo returned error 1022 Please provide 'code'.        

```
Why asking for that "code " ?

I do not have double authentication, and firewall port is open
Could you help me please ?

Thanks for you help...

**Comment by stef-pellegrino** [comment] 2024-11-25 17:05
Ok I changed the host url to handle european url too
Don't know if it's a good idea, but in my case, it does work now !

```
--- a/pclsync_lib.cpp
+++ b/pclsync_lib.cpp
@@ -41,7 +41,7 @@
 
-
+#include "pclsync/psettings.h"
 
+
+      const char *host = getenv("PCLOUD_REGION_EU") ? PSYNC_API_HOST: PSYNC_API_AHOST;
       if (psync_register(clib::pclsync_lib::get_lib().get_username().c_str(),
                          clib::pclsync_lib::get_lib().get_password().c_str(), 1,
-                         "bineapi.pcloud.com", 2, &err)) {
+                         host, 2, &err)) {

```

**Comment by lneely** [comment] 2024-11-26 07:00
@stef-pellegrino I'm pretty certain this problem came up for someone else, too. Region had entered my mind as a possibility, but I didn't take it too seriously; clearly, I should have. Thanks much for digging deeper, and for the patch; though I can only find it in email. If you don't mind, please submit a PR if you haven't already; simplifies things, and gives you due credit on GH.

I will review the code and give some thought on how to move forward. Much appreciated!

**Comment by lneely** [comment] 2024-11-27 20:48
@stef-pellegrino Interesting, we're both based in EU, and I'm not having this problem. I found the related report (#27), which also stated MFA is disabled. Right now, I simply don't know the cause, and cannot reproduce at this time.

**Comment by stef-pellegrino** [comment] 2024-11-27 21:17
Strange indeed, If I replace bineapi.pcloud.com with eapi.pcloud.com, it works.
But I don't need to do that for all of my pcloud accounts !?
I get digging (and I don't think that the problem comes from the lib...)

**Comment by lneely** [comment] 2024-11-28 17:03
The main reason I'm reluctant to change "bineapi" to "eapi" is because there may be differences in how these APIs respond. There may also not be, but it is an unknown that I lack the tools to test right now; even then, my testing is limited to my own environment.

On an unrelated note, this does bring up another good point about this code, and that is it apparently only communicates with the EU servers. Might create a low-priority ticket for adding the U.S. servers (`(bin)?api.pcloud.com`)

**Comment by lneely** [comment] 2024-12-07 10:46
@stef-pellegrino I think we have finally nailed down the nature of this problem and what needs to be done. So, I am going to close this ticket and request all future comments be made on #80. This will help me maintain focus on the actual work to be done.

**Closed by lneely** 2024-12-07 10:46 UTC
Labels: duplicate

**Comment by stef-pellegrino** [comment] 2024-12-07 10:49
Hi, Yes I didn't reproduce the case since then !? Don't know what really happened.
I'll write issue if it happens again !

Thanks for your help !

**Comment by lneely** [comment] 2024-12-07 10:50
@stef-pellegrino My point is, I think I finally understand exactly what is happening (see #80) I've added workaround notes to the README.md, and I'm hoping to find a solution through the API to support direct validation through the app. 🍻
