### ISSUE TITLE
Let's talk about authentification process

### ISSUE THREAD

**Issue by egeorgio3000** [lneely/pcloudcc-lneely#4] opened 2024-06-25 10:45 UTC
Hello ! I think opening a ticket here is more relevant than in the previous repo. So you told me about 2FA, this is an option that you can enable on your pCloud account. But I'm pretty sure this is not what i talk about. In your pCloud settings, there are a list a devices well-known by pCloud, and if you try to register with a new device pCloud send a verification email with a 8 digit code. This cause two issues. - Even if the console is stuck on status is CONNECTING, there is no confirmation mail sent to the user.
- Even if i get the code from the validation email, there is no interface to give the validation code.
These are my own deductions, i can be wrong but I think this is the issue :)

**Comment by egeorgio3000** [comment] 2024-06-25 16:57
about security, both are not enabled. I have this listed in my devices: "Laptop, Linux, pCloud CC v3.0.0	6/24/2024	6/24/2025" But this is from my computer. However, i can't connect from my VPS server and it does not appear in my devices.

It works on my computer because i did the email verification check on the web so my laptop is recognized, but i can't do the same thing on the server (this is why in need pcloudcc :) )

**Comment by lneely** [comment] 2024-06-27 05:36
Good, thanks!  I have a VPS too, so I might be able to reproduce. Will try it soon.

**Comment by lneely** [comment] 2024-06-27 21:45
@egeorgio3000 It ends up my "VPS" isn't exactly a VPS. It's more like a pubnix, but lacks the libs I need to compile and run the code and the privileges I need to install them. I'm not sure I can actually try this without paying for a VPS myself, which I am reluctant to do since I don't really need one, but I do need to be able to reproduce to know what to do next.

**Comment by lneely** [comment] 2024-08-15 21:35
@egeorgio3000 Without more information, I cannot proceed on this. Since it has been almost 2 months since the last activity on this ticket, I am going to close it. 

Please feel free to re-open it if you have any additional information. :beers:

**Closed by lneely** 2024-08-15 21:35 UTC
Labels: needs research
