### ISSUE TITLE
compilation error on ClockworkPi uConsole

### ISSUE THREAD

**Issue by lneely** [lneely/pcloudcc-lneely#22] opened 2024-07-02 12:37 UTC
Reported by @tomash

Keeping with the compilation errors, I just got a new toy, ClockworkPi uConsole which is basically a device that turns Raspberry Pi CM4 into a laptop. The operating system that came with it is Raspberry OS based on Debian 11 with kernel 5.10.17 and gcc 10.2.1, all in all pretty ancient. I've built your fork successfully on it and it works (thank you once again), but I before getting there the make was failing with the error message core2 is not a valid option for mtune, I had to edit lib/pclsync/Makefile and change the relevant part of CFLAGS to -mtune=cortex-a72. Just reporting here, not sure if it's worth fixing given those ancient versions.

**Comment by tomash** [comment] 2024-07-02 14:10
I have a regular Raspberry Pi 4B and will try to reproduce it there.

**Comment by lneely** [comment] 2024-07-02 21:34
Agree. In fact I have a plan to get rid of CMake from the build process entirely. Just don't see the need.

Almost have mbedtls working with  2.x in the mbedtls-upgrade branch The next step is 3.x, then dynamically linking mbedtls. When that's done, the entire build process will be defined in a single Makefile, as it should be.

**Comment by lneely** [comment] 2024-07-03 18:09
@tomash I removed -mtune from the CFLAGS like you suggested, this seemed like the simplest solution to me and I suspect it was a needless optimization anyway. Maybe this fixes it, mind giving it a try?

**Comment by tomash** [comment] 2024-07-04 10:59
Now it compiles smoothly without any hiccups!
We can close the issue.

It seems the reason is: GCC for different architectures has a different list of permitted values for -mtune, -march and -mcpu (although I remember compiling pcloudcc on arm machines without that issue before):

* https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html
* https://gcc.gnu.org/onlinedocs/gcc/ARM-Options.html

Still, `core2` is "Intel Core 2 CPU with 64-bit extensions, MMX, SSE, SSE2, SSE3, SSSE3, CX16, SAHF and FXSR instruction set support.", a pretty ancient architecture. When compiling for the same machine the most optimal code will be generated with `-march=native`. Don't know how to benchmark pcloudcc and if it really makes a difference -- my wild guess is it's the IO (network and disk) that's the bottleneck, not CPU, for such cloud sync software.

**Closed** 2024-07-04 11:07 UTC
Labels: bug
