### ISSUE TITLE
pcloudcc fails to connect: requests MFA code despite MFA being disabled?

### ISSUE THREAD

**Issue by ebouda33** [lneely/pcloudcc-lneely#27] opened 2024-08-01 17:00 UTC
Hi,

when I run pcloudcc
i ve this message : Down: Everything Downloaded| Up: Everything Uploaded, status is CONNECTING

but nothing else

Why no scanning ??

Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm
kernel : 6.1.0-23-cloud-amd64

**Comment by lneely** [comment] 2024-08-11 21:05
Would you mind sending me the contents of `/tmp/psync_err.log`?  I'm curious if it will contain any clues.

**Please be careful, previous versions of pcloudcc write the crypto password to this file in plain text. Redact before publishing.**

Thanks!

**Comment by ebouda33** [comment] 2024-08-12 10:43
my log
[psync_err.log](https://github.com/user-attachments/files/16580469/psync_err.log)

thanks for resolution!!

**Comment by ebouda33** [comment] 2024-08-12 11:00
my problem was the authentication code
using docker run --network host --rm -ti fathyb/carbonyl https://my.pcloud.com

everything works
thanks everyone

**Comment by lneely** [comment] 2024-09-10 14:11
@rafailml Thanks for the additional details. I found this error message in this code sample from `pdiff.c`:

```c
// ...
  res = send_command(sock, "userinfo", diffparams);
  if (!res)
    return -1;
   psync_api_conn_fail_reset();
    result = psync_find_result(res, "result", PARAM_NUM)->num;

    if (unlikely(result)) {
      debug(D_NOTICE, "userinfo returned error %lu %s", (unsigned long)result,
            psync_find_result(res, "error", PARAM_STR)->str);
      // here we only handle statuses that need to access the result
      if (result == 2297) {
        psync_free(psync_my_2fa_token);
        psync_my_2fa_token =
            psync_strdup(psync_find_result(res, "token", PARAM_STR)->str);
        psync_my_2fa_has_devices =
            psync_find_result(res, "hasdevices", PARAM_BOOL)->num;
        psync_my_2fa_type = psync_find_result(res, "tfatype", PARAM_NUM)->num;
        psync_my_2fa_code_type = 0;
        psync_my_2fa_code[0] = 0;
        psync_set_status(PSTATUS_TYPE_AUTH, PSTATUS_AUTH_TFAREQ);
        psync_wait_status(PSTATUS_TYPE_AUTH, PSTATUS_AUTH_PROVIDED);
        psync_socket_close(sock);
        psync_free(res);
        continue;
      }
// ...

I noticed that there is a function called `psync_tfa_set_code` but it isn't called anywhere. A slightly broader search shows that the only function that is actually called anywhere is `psync_tfa_send_notification()` indicating to me that 2FA support is close to non-existent in pcloudcc.

I am going to create a new feature ticket "Support 2FA", and link this ticket there. Please continue any discussions on this topic there. :beers: 

CC: @ebouda33

**Comment by rafailml** [comment] 2024-09-10 14:17
Thanks @lneely, It will be very nice support for 2FA, but in my case 2FA is turned off. It should not ask for 2FA. I'm logging in and out without 2FA.

**Comment by lneely** [comment] 2024-09-10 16:50
@rafailml Fascinating. The main notable entries I found in the log were:

```
Tue, 10 Sep 2024 12:58:13.742 +0000 721538112 main app thread NOTICE: pclsync/pfs.c:3750 (function psync_fs_start): auth status=0
...
Tue, 10 Sep 2024 12:58:13.741 +0000 721389120 Overlay main thread ERROR: pclsync/poverlay.c:116 (function psync_overlay_main_loop): Unix socket bind error
...
Tue, 10 Sep 2024 12:58:29.692 +0000 721389120 diff ERROR: pclsync/pssl.c:483 (function psync_ssl_connect_finish): handshake failed, return code was -26880
Tue, 10 Sep 2024 12:58:29.693 +0000 721389120 diff ERROR: pclsync/pssl.c:483 (function psync_ssl_connect_finish): handshake failed, return code was -26880
Tue, 10 Sep 2024 12:58:29.700 +0000 721389120 diff ERROR: pclsync/pssl.c:483 (function psync_ssl_connect_finish): handshake failed, return code was -26880
...
Tue, 10 Sep 2024 12:58:29.805 +0000 721389120 diff NOTICE: pclsync/pdiff.c:424 (function get_connected_socket): userinfo returned error 1022 Please provide 'code'.
...
Tue, 10 Sep 2024 12:58:35.963 +0000 721389120 diff NOTICE: pclsync/pdiff.c:424 (function get_connected_socket): userinfo returned error 1022 Please provide 'code'.
```

At this point we have a few options to investigate:
- The unix socket error
- The SSL handshake error
- The userinfo error

I notice that the userinfo returns error `1022` but the only status that has anything to do with freeing the 2fa token is `2297`. That leads me to believe that, as you say, it has nothing to do with 2FA, and the error message is misleading.

Looking at the userinfo endpoint on pcloud API docs: https://docs.pcloud.com/methods/general/userinfo.html

```
Code	Description
1000	Log in required.
2000	Log in failed.
4000	Too many login tries from this IP address.
```

The closest thing to `1022` is `1000` indicating a login is required.

This suggest to me that the unix socket error may be irrelevant for now; it could impact the ability of the CLI program to interact with the API (SendCall would likely fail), but it does not appear to be directly related to this problem.

The other two problems appear to be related: your login request is likely failing because of an SSL handshake error, and you're stuck in CONNECTING because the login failed.

I have attempted in the past to reproduce this problem and have consistently failed. I've run an Ubuntu 22.04 dev host, compiled and run the program normally there. Same with a standard Ubuntu desktop distribution.

I need more info, and I'm honestly not certain where to start. For now, I will do some research and see if I can't find any notable differences between the server and desktop versions of Ubuntu 22.04 (e.g., server distributions tend to be more hardened than desktop...)

**Comment by lneely** [comment] 2024-09-10 17:27
Interesting. I set up my `openssl.cnf` to emulate the Server distribution as best as I could, and I was able to reproduce the ssl handshake errors.

Note to self: relevant configuration settings

```
openssl_conf = openssl_init

[openssl_init]
ssl_conf = ssl_sect

[ssl_sect]
system_default = system_default_sect

[system_default_sect]
CipherString = DEFAULT:@SECLEVEL=2
```

Still, I failed to reproduce the error. The next item on my checklist is firewall settings. Typically server distributions disallow all except SSH on incoming, and require you to whitelist the allowed ports. My question at this point is, would one need to run something like:

`sudo ufw allow https`

I will need to set up a VM to test this theory. I will do that some other time, it's getting late here. :)

**Comment by rafailml** [comment] 2024-09-10 17:42
433 was already open. Same thing.

**Comment by lneely** [comment] 2024-09-10 18:49
OK, this was bugging me so I went ahead and tried with a VM.  Both "live" image of Ubuntu Server 22.04 and "legacy" image of Ubuntu Server 22.04. Under both versions, `pcloudcc` worked as expected. It worked when I had ufw enabled, and it worked with the cipher configuration as previously mentioned in `openssl.cnf`. 

I still cannot help but think there is a configuration setting that is causing this error, but I'll be damned if I know what it is. My assumption is that Ubuntu is Ubuntu, regardless of whether server or desktop (i.e., same mbedtls version, etc.) differing only in configuration.

Any help with this is appreciated, even just pointers in a direction.

**Comment by mawi42** [comment] 2024-10-12 12:34
Hi,
I have actually the same issue since some month, today i checked my log and also have the error 1022. However I know the reason why it is not working on my side and know that the frozen state is somehow missleading. 
I run it on a v-server where a older kernel is running Ubuntu 22.04 (5.2.0-1160.105.1.vz7.214.3) . Before on even older Ubuntu 20.04 everythin was fine. In fact the mount fails for user space (as often reported also for other pcloudcc forks), if you test `modprobe fuse` I got error
modprobe: FATAL: Module fuse not found in directory /lib/modules/5.2.0-1160.105.1.vz7.214.3.
I tried at that time a lot of hints install latest fuse .... nothing solved my yproblem and actually I am not such a Linux expert to solve it. Unfortunate kernel upgrade is not possible in the v-server, also running in own docker finally fails for the mount.

Maybe this helps you at least to confirm the same error.
However I do not expect that there is a simple solution. (my not so nice workaround is now a fsnyc the v-server form my local Linux where the pcloudcc mounts well)

mawi

**Comment by rafailml** [comment] 2024-10-17 17:34
Just tested on new server with Ubuntu 22.04 - same error :(

**Comment by ebouda33** [comment] 2024-10-17 17:54
Use the docker image to obtain the code
Look here
https://github.com/lneely/pcloudcc-lneely/issues/27#issuecomment-2283665317

it s a protection if your server is not in the same geographical zone of your pCloud zone

**Comment by rafailml** [comment] 2024-10-17 18:09
@ebouda33 , sorry, I can't understand you. What code to obtain? I have no 2FA enabled in pCloud.
And what is the point to run 
```docker run --network host --rm -ti fathyb/carbonyl https://my.pcloud.com/```
what does this image fathyb/carbonyl do?

**Comment by ebouda33** [comment] 2024-10-17 18:43
It s n 2fa
Just Run the docker command
It s open a navigator follow screen
You will receive a code on your account pCloud by mail
Put the code on the navigator open by docker 
And that all folks!!!!

**Comment by rafailml** [comment] 2024-10-18 13:20
Thanks @ebouda33 !!!! This works!!!

**Comment by ajabusch** [comment] 2024-11-26 09:33
Thanks so much. :+1:  But it would be great if the tool could tell us what it needs and it would be great if it was less complicated. 
Long key instead of 2FA or another type of 2FA (tool displays an URL, URL sends you to your account ...).
Using a docker container to simulate a graphical browser to browse to a page, to get an email, to get a code, to ... is not that headless. :smile: 
Just my two cents.

**Comment by tomash** [comment] 2024-12-02 11:44
Confirming this issue, it's pCloud enforcing typing code sent to email even when 2FA is disabled.
The workaround from @ebouda33 to run dockerized Carbonyl and type the code there (so that pCloud trusts a given host) works. Maybe worth adding to readme until the actual `pcloudcc` code supports typing in this code?

**Comment by lneely** [comment] 2024-12-03 19:58
@tomash Thanks for the confirmation. Your explanation makes sense, but I'm puzzled as to why I'm not having the same problem. Perhaps it's something they're deploying in phases? I will bump priority up on the 2FA ticket (#68).

**Comment by rafailml** [comment] 2024-12-04 07:23
@lneely if you have browser - OK, in my case I'm running pcludcc on server, and docker is my only option.

**Comment by lneely** [comment] 2024-12-07 10:07
All:  I think I've finally understood the nature of this problem. Contrary to what I was thinking, it is NOT 2FA. This has also revealed a few assumptions I made without being consciously aware of:

- Users are running on devices already known to and trusted by pcloud.com
- Users are running pcloudcc on "standard" desktop devices with web browsing capabilities
- If the user must login to pcloud.com to validate and trust the device, they can simply do so in their web browser.

Your feedback tells me that these assumptions are false. Based on all of the feedback I've read, I will add some notes to the README including reported workarounds to assist with these use cases as @tomash suggested. I will also open a new ticket to investigate a way to validate these devices using the API and, if possible, implement.

**Comment by lneely** [comment] 2024-12-07 10:45
All:  Since I think we have finally nailed down the nature of this problem and what needs to be done, I am going to close this ticket and request all future comments be made on #80.

**Closed by lneely** 2024-12-07 10:45 UTC
Labels: bug, help wanted
